#!/usr/bin/env bash
# Configures a new Ubuntu server

apt-get -y update
apt-get -y install nginx

ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sed -i "/^\tlocation \/ {.*/a \\\t \tadd_header X-Served-By \$hostname;" /etc/nginx/sites-available/default
sed -i '/^\tserver_name _.*/a \\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sed -i '/^\tserver_name _.*/a \\terror_page 404 /custom_404.html;' /etc/nginx/sites-available/default

service nginx restart
