#!/usr/bin/env bash
#Install and configure HAproxy on a server

sudo apt-get -y update
sudo apt-get -y install haproxy

echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 376145-web-01 18.235.243.105:80 check
   server 376145-web-02 34.203.38.189:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null

sudo service haproxy restart
