#!/usr/bin/env bash
# script that display and create the pid file
echo $$ >> /var/run/myscript.pid

trap 'echo I hate the kill command; rm -f /var/run/myscript.pid; exit 1' SIGTERM
trap 'rm -f /var/run/myscript.pid; exit 1' SIGQUIT
trap "echo Y U no love me?!" SIGINT

while true;
	do
		echo "To infinity and beyond"
		sleep 2;
done;
