#!/usr/bin/env bash
# script that display and create the pid file
echo $$ >> /var/run/myscript.pid
while true;
	do
		echo "To infinity and beyond"
		sleep 2;
		trap 'echo "Y U no love me?!"' SIGINT
		trap 'echo "I hate the kill command" && terminator' SIGTERM
		trap 'terminator' SIGQUITgit 
done;
