#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd, showing specific information.
while IFS=':' read -r username x uid gid description home shell; do
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $x, more info about the user here: $description"
done < /etc/passwd
