#!/usr/bin/env bash
# displays messages based on specific loop iterations.
count=1

while [ $count -le 20 ]; do
    case $count in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
        *)
            echo $count
            ;;
    esac
    ((count++))
done

